# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a941272f9d884106470f401c54df516b44828dbe14f8235913df8f2d1b2f07c490a8d457d52d206568e9b605d991f5ab5646912bd7a5f442c77c8549530c03

test:
  secret_key_base: 972a07c0a356ee4127965c6ca9f72e34fdab0015bb88f15952e9a58e4d2e81f7d06c56f3fa00eb14a33f565fadc1d86188cbffe71a4794f92f02f27d7d8fea2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
